# Generated by Django 2.1.7 on 2019-05-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackers_app', '0002_user_real_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='time',
        ),
    ]
